# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyogi Karuta
email: stampaa@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  競技かるた (Kyogi Karuta) es un deporte tradicional japonés de cartas basados en una antología de poemas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: 573ph
github_username:  droxine
permalink: pretty
# Build settings
markdown: kramdown
